env:
  browser: true
  es6: true
  jest: true
  node: true

extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/eslint-recommended'
  - 'plugin:react/recommended'
  - 'plugin:react-hooks/recommended'
  - 'plugin:jsx-a11y/recommended'

ignorePatterns:
  - 'node_modules/*'
  - '.yarn/*'
  - '.next/*'
  - '.out/*'
  - 'api/generated/*'
  - 'generated/*'

parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2021
  ecmaFeatures:
    jsx: true

plugins:
  - 'react'
  - 'react-hooks'
  - '@typescript-eslint'

rules:
  react/prop-types: 0
  react/react-in-jsx-scope: 0
  react/jsx-props-no-spreading: 0
  jsx-a11y/anchor-is-valid: 0
  react/jsx-one-expression-per-line: 0
  react/no-unescaped-entities: 0
  no-param-reassign: 0
  no-unused-vars: 0
  '@typescript-eslint/no-unused-vars': ['error', { 'argsIgnorePattern': '^_' }]

settings:
  react:
    version: 'detect'
  import/resolver:
    node:
      extensions:
        - '.js'
        - '.jsx'
        - '.ts'
        - '.tsx'
