export const languages = [
  {
    language: 'Mandarin',
    country: 'China',
    continent: 'Asia',
    population: 885000000,
  },
  {
    language: 'Spanish',
    country: 'Spain',
    continent: 'Europe',
    population: 332000000,
  },
  {
    language: 'English',
    country: 'United Kingdom',
    continent: 'Europe',
    population: 322000000,
  },
  {
    language: 'Bengali',
    country: 'Bangladesh',
    continent: 'Asia',
    population: 189000000,
  },
  {
    language: 'Hindi',
    country: 'India',
    continent: 'Asia',
    population: 182000000,
  },
  {
    language: 'Portuguese',
    country: 'Portugal',
    continent: 'Europe',
    population: 170000000,
  },
  {
    language: 'Russian',
    country: 'Russia',
    continent: 'Europe',
    population: 170000000,
  },
  {
    language: 'Japanese',
    country: 'Japan',
    continent: 'Asia',
    population: 125000000,
  },
  {
    language: 'German',
    country: 'Germany',
    continent: 'Europe',
    population: 98000000,
  },
  {
    language: 'Chinese',
    country: 'China',
    continent: 'Asia',
    population: 77175000,
  },
  {
    language: 'Javanese',
    country: 'Indonesia, Java, Bali',
    continent: 'Asia',
    population: 75500800,
  },
  {
    language: 'Korean',
    country: 'Korea, South',
    continent: 'Asia',
    population: 75000000,
  },
  {
    language: 'French',
    country: 'France',
    continent: 'Europe',
    population: 72000000,
  },
  {
    language: 'Vietnamese',
    country: 'Viet Nam',
    continent: 'Asia',
    population: 67662000,
  },
  {
    language: 'Telugu',
    country: 'India',
    continent: 'Asia',
    population: 66350000,
  },
  {
    language: 'Yue Chinese',
    country: 'China',
    continent: 'Asia',
    population: 66000000,
  },
  {
    language: 'Marathi',
    country: 'India',
    continent: 'Asia',
    population: 64783000,
  },
  {
    language: 'Tamil',
    country: 'India',
    continent: 'Asia',
    population: 63075000,
  },
  {
    language: 'Turkish',
    country: 'Turkey',
    continent: 'Asia',
    population: 59000000,
  },
  {
    language: 'Urdu',
    country: 'Pakistan',
    continent: 'Asia',
    population: 58000000,
  },
  {
    language: 'Min',
    country: 'China',
    continent: 'Asia',
    population: 49000000,
  },
  {
    language: 'Gujarati',
    country: 'India',
    continent: 'Asia',
    population: 44000000,
  },
  {
    language: 'Polish',
    country: 'Poland',
    continent: 'Europe',
    population: 44000000,
  },
  {
    language: 'Arabic',
    country: 'Egypt',
    continent: 'Asia',
    population: 42500000,
  },
  {
    language: 'Ukranian',
    country: 'Ukraine',
    continent: 'Europe',
    population: 41000000,
  },
  {
    language: 'Italian',
    country: 'Italy',
    continent: 'Europe',
    population: 37000000,
  },
  {
    language: 'Malayalam',
    country: 'India',
    continent: 'Asia',
    population: 34022000,
  },
  {
    language: 'Hakka Chinese',
    country: 'China',
    continent: 'Asia',
    population: 34000000,
  },
  {
    language: 'Kannada',
    country: 'India',
    continent: 'Asia',
    population: 33663000,
  },
  {
    language: 'Oriya',
    country: 'India',
    continent: 'Asia',
    population: 31000000,
  },
  {
    language: 'Punjabi',
    country: 'Pakistan',
    continent: 'Asia',
    population: 30000000,
  },
  {
    language: 'Sunda',
    country: 'Indonesia',
    continent: 'Asia',
    population: 27000000,
  },
  {
    language: 'Romanian',
    country: 'Romania',
    continent: 'Europe',
    population: 26000000,
  },
  {
    language: 'Bhojpuri',
    country: 'India',
    continent: 'Asia',
    population: 25000000,
  },
  {
    language: 'Azerbaijani',
    country: 'Iran',
    continent: 'Asia',
    population: 24364000,
  },
  {
    language: 'Fasi',
    country: 'Iran',
    continent: 'Asia',
    population: 24280000,
  },
  {
    language: 'Maithili',
    country: 'India',
    continent: 'Asia',
    population: 24260000,
  },
  {
    language: 'Hausa',
    country: 'Nigeria',
    continent: 'Africa',
    population: 24200000,
  },
  {
    language: 'Burmese',
    country: 'Myanmar',
    continent: 'Asia',
    population: 22000000,
  },
  {
    language: 'Serbo-Croatian',
    country: 'Yugoslavia',
    continent: 'Europe',
    population: 21000000,
  },
  {
    language: 'Awadhi',
    country: 'India',
    continent: 'Asia',
    population: 20540000,
  },
  {
    language: 'Thai',
    country: 'Thailand',
    continent: 'Asia',
    population: 20047000,
  },
  {
    language: 'Dutch',
    country: 'Netherlands',
    continent: 'Europe',
    population: 20000000,
  },
  {
    language: 'Yoruba',
    country: 'Nigeria',
    continent: 'Africa',
    population: 20000000,
  },
  {
    language: 'Sindhi',
    country: 'Pakistan',
    continent: 'Asia',
    population: 19720000,
  },
  {
    language: 'Uzbek',
    country: 'Uzbekistan',
    continent: 'Asia',
    population: 18466000,
  },
  {
    language: 'Malay',
    country: 'Malaysia, Peninsular',
    continent: 'Asia',
    population: 17600000,
  },
  {
    language: 'Amharic',
    country: 'Ethiopia',
    continent: 'Africa',
    population: 17413000,
  },
  {
    language: 'Indonesian',
    country: 'Indonesia',
    continent: 'Asia',
    population: 17050000,
  },
  {
    language: 'Igbo',
    country: 'Nigeria',
    continent: 'Africa',
    population: 17000000,
  },
  {
    language: 'Tagalog',
    country: 'Philippines',
    continent: 'Asia',
    population: 17000000,
  },
  {
    language: 'Nepali',
    country: 'Nepal',
    continent: 'Asia',
    population: 16056000,
  },
  {
    language: 'Saraki',
    country: 'Pakistan',
    continent: 'Asia',
    population: 15015000,
  },
  {
    language: 'Cebuano',
    country: 'Philippines',
    continent: 'Asia',
    population: 15000000,
  },
  {
    language: 'Assamese',
    country: 'India',
    continent: 'Asia',
    population: 14634000,
  },
  {
    language: 'Hungarian',
    country: 'Hungary',
    continent: 'Europe',
    population: 14500000,
  },
  {
    language: 'Chittagonian',
    country: 'Bangladesh',
    continent: 'Asia',
    population: 14000000,
  },
  {
    language: 'Madura',
    country: 'Indonesia, Java, Bali',
    continent: 'Asia',
    population: 13694000,
  },
  {
    language: 'Sinhala',
    country: 'Sri Lanka',
    continent: 'Asia',
    population: 13220000,
  },
  {
    language: 'Haryanvi',
    country: 'India',
    continent: 'Asia',
    population: 13000000,
  },
  {
    language: 'Marwari',
    country: 'India',
    continent: 'Asia',
    population: 12104000,
  },
  {
    language: 'Czech',
    country: 'Czech Republic',
    continent: 'Europe',
    population: 12000000,
  },
  {
    language: 'Greek',
    country: 'Greece',
    continent: 'Europe',
    population: 12000000,
  },
  {
    language: 'Magahi',
    country: 'India',
    continent: 'Asia',
    population: 12000000,
  },
  {
    language: 'Chhattisgarhi',
    country: 'India',
    continent: 'Asia',
    population: 10985000,
  },
  {
    language: 'Deccan',
    country: 'India',
    continent: 'Asia',
    population: 10709800,
  },
  {
    language: 'Belarusan',
    country: 'Belarus',
    continent: 'Europe',
    population: 10200000,
  },
  {
    language: 'Zhuang',
    country: 'China',
    continent: 'Asia',
    population: 10000000,
  },
  {
    language: 'Pashto',
    country: 'Pakistan',
    continent: 'Asia',
    population: 9685000,
  },
  {
    language: 'Somali',
    country: 'Somalia',
    continent: 'Africa',
    population: 9472000,
  },
  {
    language: 'Malagasy',
    country: 'Madagascar',
    continent: 'Africa',
    population: 9398700,
  },
  {
    language: 'Rwanda',
    country: 'Rwanda',
    continent: 'Africa',
    population: 9306800,
  },
  {
    language: 'Zulu',
    country: 'South Africa',
    continent: 'Africa',
    population: 9142000,
  },
  {
    language: 'Bulgarian',
    country: 'Bulgaria',
    continent: 'Europe',
    population: 9000000,
  },
  {
    language: 'Swedish',
    country: 'Sweden',
    continent: 'Europe',
    population: 9000000,
  },
  {
    language: 'Lombard',
    country: 'Italy',
    continent: 'Europe',
    population: 8974000,
  },
  {
    language: 'Oromo',
    country: 'Ethiopia',
    continent: 'Africa',
    population: 8920000,
  },
  {
    language: 'Kazakh',
    country: 'Kazakhstan',
    continent: 'Asia',
    population: 8000000,
  },
  {
    language: 'Ilocano',
    country: 'Philippines',
    continent: 'Asia',
    population: 8000000,
  },
  {
    language: 'Tatar',
    country: 'Russia',
    continent: 'Europe',
    population: 8000000,
  },
  {
    language: 'Fulfulde',
    country: 'Nigeria',
    continent: 'Africa',
    population: 7611000,
  },
  {
    language: 'Uyghur',
    country: 'China',
    continent: 'Asia',
    population: 7595512,
  },
  {
    language: 'Haitian',
    country: 'Haiti',
    continent: 'Africa',
    population: 7372000,
  },
  {
    language: 'Khmer',
    country: 'Cambodia',
    continent: 'Asia',
    population: 7039200,
  },
  {
    language: 'Akan',
    country: 'Ghana',
    continent: 'Africa',
    population: 7000000,
  },
  {
    language: 'Hiligaynon',
    country: 'Philippines',
    continent: 'Asia',
    population: 7000000,
  },
  {
    language: 'Kurmanji',
    country: 'Turkey',
    continent: 'Asia',
    population: 7000000,
  },
  {
    language: 'Shona',
    country: 'Zimbabwe',
    continent: 'Africa',
    population: 7000000,
  },
];
