export const mentees = [
  {
    name: 'Steven Du',
    bio: 'Very good strong man who loves a good engineering shift.',
    job_title_primary: 'Engineer',
    job_title_secondary: 'Embedded Systems',
    preferred_services: ['RESUME_CRITIQUE', 'GENERAL', 'SUCCESS_AT_WORK'],
    school: ['McMaster University'],
    school_major: 'Statistics',
    school_year: 1923,
    degree_type: 'B.SC',
  },
  {
    name: 'Jesse Drummond',
    bio: 'Computer scientist specializing in the backend of web',
    job_title_primary: 'Computer Scientist',
    job_title_secondary: 'Web Developer',
    preferred_services: ['RESUME_CRITIQUE', 'SKILLS_FOR_SUCCESS'],
    school: 'Lakehead University',
    school_major: 'Computer Science',
    school_year: 2017,
    degree_type: 'B.SC',
  },
  {
    name: 'Carolyn Ignacio',
    bio: 'HR prospect',
    job_title_primary: 'Internship',
    job_title_secondary: 'Advanced Analytics',
    preferred_services: ['CAREER_DEVELOPMENT', 'RESUME_CRITIQUE'],
    school: 'Brock University',
    school_major: 'Statistics',
    school_year: 2019,
    degree_type: 'B.SC',
  },
];
