export const mentors = [
  {
    name: 'Atinder Bharaj',
    bio: 'Very good data scientist with 5+ years of experience',
    job_title_primary: 'Data Scientist I',
    job_title_secondary: 'Personal Banking',
    preferred_services: ['RESUME_CRITIQUE', 'GENERAL', 'SUCCESS_AT_WORK'],
    school: ['McMaster University'],
    school_major: 'Statistics',
    school_year: 1923,
    degree_type: 'B.SC',
  },
  {
    name: 'Dustin Jurkaulionis',
    bio: 'Computer scientist with 2+ years of experience',
    job_title_primary: 'Computer Scientist',
    job_title_secondary: 'Web Developer',
    preferred_services: ['CAREER_DEVELOPMENT', 'MOCK_INTERVIEW'],
    school: 'McMaster University',
    school_major: 'Computer Science',
    school_year: 2019,
    degree_type: 'B.SC',
  },
  {
    name: 'Jane Doe',
    bio: 'Specializing in Wealth Advanced Analytics ',
    job_title_primary: 'Computer Scientist',
    job_title_secondary: 'Web Developer',
    preferred_services: ['CAREER_DEVELOPMENT', 'MOCK_INTERVIEW'],
    school: 'McMaster University',
    school_major: 'Computer Science',
    school_year: 2019,
    degree_type: 'B.SC',
  },
];
