export const skills = [
  {
    skill: '.NET Framework',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Adaptability',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Administrative',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Adobe Animate',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Adobe Illustrator',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Adobe InDesign',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Adobe Lightroom',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Adobe Photoshop',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Adobe Premiere Pro',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Adobe XD',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['UI_UX'],
    purpose: ['UI_UX'],
  },
  {
    skill: 'After Effects',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Agile Methodologies',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST, DEVELOPER'],
    purpose: ['ANALYST', 'WEB_DEVELOPMENT', 'DATA_SCIENCE'],
  },
  {
    skill: 'Amazone Web Services',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_STORAGE'],
  },
  {
    skill: 'Analytical Reasoning',
    skill_type: 'SOFT',
    family: 'QUANTITATIVE',
    role: ['ANALYST'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'Android Angular JS',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['APP_DEVELOPER'],
  },
  {
    skill: 'Animation',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'ArcGIS Products',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Artificial Intelligence (AI)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST, DEVELOPER'],
    purpose: ['DATA_SCIENCE, SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'AutoCAD',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Autodesk Fusion 360',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Autodesk Inventor',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Avid Media Composer',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'AWS Lambda',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Bash',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Blockchain',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Business Analysis',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Business Development',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'Business Intelligence',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'Business Management',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Business Storytelling',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'C',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'C#',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'C++',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Cascading Style Sheets (CSS)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Channel Marketing',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Cloud Computing',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Coaching',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Collaboration',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Competitive Strategies',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Computer Graphics',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['MEDIA_DESIGN', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Consulting',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Content Management',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Content Marketing',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Content Strategy',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Corporate Communications',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Creativity',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Critical thinking',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'Customer Relationship Management (CRM) Software',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Customer Service Systems',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Data Analytics',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Data Visualization',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Database Administration',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Delegating Tasks',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Digital Marketing',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Digital Media',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Django',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Dreamweaver',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Eclipse',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Economics',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Emotional Intelligence (EQ)',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Final Cut Pro',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Git',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT', 'WEB_DEVELOPMENT'],
  },
  {
    skill: 'Google Analytics',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Google Cloud Platform (GCP)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Hadoop',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'HTML',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'iMovie',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Industrial Design',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Java',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'JavaScript',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Journalism',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'jQuery',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'JSON',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Keynote',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['PRESENTATION'],
  },
  {
    skill: 'Kotlin',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Leadership',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Logic Pro',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Market Research',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'MATLAB',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Maven',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Maya',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Media Planning',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Microsoft Access',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['DEVELOPER'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Microsoft Azure',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Microsoft Power Automate',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Microsoft Power BI',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Microsoft PowerPoint',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['PRESENTATION'],
  },
  {
    skill: 'Microsoft Project',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['PRESENTATION'],
  },
  {
    skill: 'Microsoft Word',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['DOCUMENTATION'],
  },
  {
    skill: 'Middleware and Integration Software',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Mobile Application Development',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Mobile Development',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'MongoDB',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'MySQL',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Natural Language Processing',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Negotiation',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Network and Information Security',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Node.js',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'NoSQL',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST DEVELOPER'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Object-Oriented Programming (OOP)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Objective-C',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Online Marketing',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['ANALYST', 'MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'People Management',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Persuasion',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'PHP',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Pro Tools',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Problem-solving',
    skill_type: 'SOFT',
    family: 'QUANTITATIVE',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['ANALYST', 'DATA_SCIENCE'],
  },
  {
    skill: 'Project Management',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Public Relations',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['MARKETING'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Python',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'R/RStudio',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'React.js',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Relationship Management',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['MANAGER'],
  },
  {
    skill: 'Research',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'REST APIs',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Revit',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['ARCHITECT'],
  },
  {
    skill: 'Rhino 3D',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['DESIGNER'],
    purpose: ['ARCHITECT'],
  },
  {
    skill: 'Ruby on Rails',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Sales Leadership',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Scala',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Scientific Computing',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['DATA_SCIENCE'],
  },
  {
    skill: 'Search Engine Optimization (SEO)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'SharePoint',
    skill_type: 'HARD',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['DOCUMENTATION'],
  },
  {
    skill: 'SketchUp',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['DESIGNER'],
    purpose: ['GRAPHIC_DESIGN'],
  },
  {
    skill: 'Social Media',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['DESIGNER'],
    purpose: ['MARKETING'],
  },
  {
    skill: 'Software Engineering',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Software Management',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Software Testing',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'SOLIDWORKS',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT', 'GRAPHIC_DESIGN'],
  },
  {
    skill: 'Spring Framework',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Storage Systems and Management',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Strategic Planning',
    skill_type: 'HARD',
    family: 'QUANTITATIVE',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Swift',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Tech Support',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Time Management',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['TRAIT'],
  },
  {
    skill: 'Transact-SQL (T-SQL)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'DATA_STORAGE', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Translation',
    skill_type: 'SOFT',
    family: 'GENERAL',
    role: ['EVERYONE'],
    purpose: ['HUMAN_RESOURCES'],
  },
  {
    skill: 'Unity',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'User Interface Design',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['UI_UX'],
  },
  {
    skill: 'UX Design',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['GRAPHIC_DESIGNER'],
    purpose: ['UI_UX'],
  },
  {
    skill: 'Video Production',
    skill_type: 'HARD',
    family: 'MULTIMEDIA',
    role: ['MEDIA_DESIGNER'],
    purpose: ['MEDIA_DESIGN'],
  },
  {
    skill: 'Visio',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST', 'DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'WEB_DEVELOPMENT', 'SOFTWARE_DEVELOPMENT'],
  },
  {
    skill: 'Visual Basic for Applications (VBA)',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['ANALYST'],
    purpose: ['ANALYST'],
  },
  {
    skill: 'Web Architecture and Development Framework',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'Windows Server',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['DATA_SCIENCE', 'WEB_DEVELOPMENT'],
  },
  {
    skill: 'WordPress',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
  {
    skill: 'XML',
    skill_type: 'HARD',
    family: 'PROGRAMMING',
    role: ['DEVELOPER'],
    purpose: ['WEB_DEVELOPMENT'],
  },
];
