export const universities = [
  {
    name: 'Université de Montréal',
    city: ['Montreal'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '41055',
    postgrad_count: '14485',
    total_count: '55540',
    year_founded: '1878',
    size_score: '3',
  },
  {
    name: 'Université du Québec à Montréal',
    city: ['Montreal'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '33100',
    postgrad_count: '6570',
    total_count: '41670',
    year_founded: '1969',
    size_score: '3',
  },
  {
    name: 'Université Laval',
    city: ['Quebec City'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '27530',
    postgrad_count: '10270',
    total_count: '37800',
    year_founded: '1663',
    size_score: '3',
  },
  {
    name: 'Université de Sherbrooke',
    city: ['Sherbrooke'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '13490',
    postgrad_count: '6010',
    total_count: '19500',
    year_founded: '1954',
    size_score: '3',
  },
  {
    name: 'Université du Québec à Trois-Rivières',
    city: ['Trois-Rivières'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '9160',
    postgrad_count: '1450',
    total_count: '10610',
    year_founded: '1969',
    size_score: '2',
  },
  {
    name: 'École de technologie supérieure',
    city: ['Montreal'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '7480',
    postgrad_count: '3180',
    total_count: '10600',
    year_founded: '1974',
    size_score: '2',
  },
  {
    name: 'Université du Québec à Chicoutimi',
    city: ['Chicoutimi'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '5140',
    postgrad_count: '1030',
    total_count: '6170',
    year_founded: '1969',
    size_score: '2',
  },
  {
    name: 'Université de Moncton',
    city: ['Moncton', 'Shippagan', 'Edmundston'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '5281',
    postgrad_count: '683',
    total_count: '5964',
    year_founded: '1963',
    size_score: '2',
  },
  {
    name: 'Université du Québec en Outaouais',
    city: ['Gatineau', 'Saint-Jérôme'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '4360',
    postgrad_count: '1090',
    total_count: '5450',
    year_founded: '1970',
    size_score: '2',
  },
  {
    name: 'Université du Québec à Rimouski',
    city: ['Rimouski and Lévis'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '4620',
    postgrad_count: '810',
    total_count: '5430',
    year_founded: '1969',
    size_score: '2',
  },
  {
    name: 'Université du Québec en Abitibi-Témiscamingue',
    city: ['Rouyn-Noranda', 'Mont-Laurier'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '2260',
    postgrad_count: '390',
    total_count: '2650',
    year_founded: '1970',
    size_score: '1',
  },
  {
    name: "École nationale d'administration publique",
    city: ['Quebec City', 'Montreal', 'Gatineau', 'Saguenay', 'Trois-Rivières'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '0',
    postgrad_count: '1880',
    total_count: '1880',
    year_founded: '1969',
    size_score: '1',
  },
  {
    name: 'Institut national de la recherche scientifique',
    city: ['Quebec City', 'Montreal', 'Laval', 'Varennes'],
    province: 'Quebec',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '0',
    postgrad_count: '480',
    total_count: '480',
    year_founded: '1969',
    size_score: '1',
  },
  {
    name: 'Université Sainte-Anne',
    city: ["Pointe-de-l'Église"],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '435',
    postgrad_count: '20',
    total_count: '455',
    year_founded: '1890',
    size_score: '1',
  },
  {
    name: "Université de l'Ontario français",
    city: ['Toronto'],
    province: 'Ontario',
    country: 'Canada',
    language: 'French',
    category: 'Public',
    undergrad_count: '0',
    postgrad_count: '0',
    total_count: '0',
    year_founded: '2018',
    size_score: '1',
  },
  {
    name: 'University of Regina',
    city: ['Regina', 'Saskatoon', 'Swift Current'],
    province: 'Saskatchewan',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '10690',
    postgrad_count: '1480',
    total_count: '12170',
    year_founded: '1911',
    size_score: '2',
  },
  {
    name: 'York University',
    city: ['Toronto'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '46624',
    postgrad_count: '5662',
    total_count: '52286',
    year_founded: '1959',
    size_score: '3',
  },
  {
    name: 'University of Toronto',
    city: ['Toronto (St. George)', 'Scarborough', 'Mississauga'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '65991',
    postgrad_count: '18167',
    total_count: '84158',
    year_founded: '1827',
    size_score: '3',
  },
  {
    name: 'Carleton University',
    city: ['Ottawa'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '25290',
    postgrad_count: '4071',
    total_count: '29361',
    year_founded: '1942',
    size_score: '3',
  },
  {
    name: 'University of British Columbia',
    city: ['Vancouver', 'Kelowna'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '41700',
    postgrad_count: '8630',
    total_count: '50330',
    year_founded: '1908',
    size_score: '3',
  },
  {
    name: 'Concordia University',
    city: ['Montreal'],
    province: 'Quebec',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '32347',
    postgrad_count: '6462',
    total_count: '43944',
    year_founded: '1974',
    size_score: '3',
  },
  {
    name: 'Athabasca University',
    city: ['Athabasca', 'Calgary', 'Edmonton'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '36240',
    postgrad_count: '3460',
    total_count: '39700',
    year_founded: '1970',
    size_score: '3',
  },
  {
    name: 'Ryerson University',
    city: ['Toronto'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '36100',
    postgrad_count: '2623',
    total_count: '38723',
    year_founded: '1948',
    size_score: '3',
  },
  {
    name: 'University of Waterloo',
    city: ['Waterloo', 'Cambridge', 'Kitchener', 'Stratford'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '32143',
    postgrad_count: '5827',
    total_count: '37970',
    year_founded: '1957',
    size_score: '3',
  },
  {
    name: 'University of Western Ontario',
    city: ['London'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '30159',
    postgrad_count: '6390',
    total_count: '36549',
    year_founded: '1878',
    size_score: '3',
  },
  {
    name: 'Simon Fraser University',
    city: ['Burnaby', 'Surrey', 'Vancouver'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '29697',
    postgrad_count: '5507',
    total_count: '35204',
    year_founded: '1965',
    size_score: '3',
  },
  {
    name: 'McGill University',
    city: ['Montreal', 'Ste-Anne-de-Bellevue'],
    province: 'Quebec',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '23758',
    postgrad_count: '8756',
    total_count: '32514',
    year_founded: '1821',
    size_score: '3',
  },
  {
    name: 'McMaster University',
    city: ['Hamilton'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '26504',
    postgrad_count: '4513',
    total_count: '31017',
    year_founded: '1887',
    size_score: '3',
  },
  {
    name: 'University of Calgary',
    city: ['Calgary', 'Edmonton'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '23320',
    postgrad_count: '6540',
    total_count: '29860',
    year_founded: '1966',
    size_score: '3',
  },
  {
    name: 'University of Guelph',
    city: ['Guelph', 'Toronto', 'Alfred', 'Ridgetown', 'Kemptville'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '26251',
    postgrad_count: '2818',
    total_count: '29069',
    year_founded: '1964',
    size_score: '3',
  },
  {
    name: 'Mount Royal University',
    city: ['Calgary'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '24768',
    postgrad_count: '0',
    total_count: '24768',
    year_founded: '1910',
    size_score: '3',
  },
  {
    name: "Queen's University at Kingston",
    city: ['Kingston'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '19738',
    postgrad_count: '4889',
    total_count: '24627',
    year_founded: '1841',
    size_score: '3',
  },
  {
    name: 'University of Victoria',
    city: ['Victoria'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '18863',
    postgrad_count: '3542',
    total_count: '22405',
    year_founded: '1963',
    size_score: '3',
  },
  {
    name: 'Memorial University of Newfoundland',
    city: ["St. John's", 'Corner Brook', 'Harlow (United Kingdom)'],
    province: 'Newfoundland and Labrador',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '15418',
    postgrad_count: '3495',
    total_count: '18913',
    year_founded: '1925',
    size_score: '3',
  },
  {
    name: 'MacEwan University',
    city: ['Edmonton'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '18897',
    postgrad_count: '0',
    total_count: '18897',
    year_founded: '1971',
    size_score: '3',
  },
  {
    name: 'University of Saskatchewan',
    city: ['Saskatoon'],
    province: 'Saskatchewan',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '16430',
    postgrad_count: '2190',
    total_count: '18620',
    year_founded: '1907',
    size_score: '3',
  },
  {
    name: 'Dalhousie University',
    city: ['Halifax', 'Truro'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '14423',
    postgrad_count: '3931',
    total_count: '18354',
    year_founded: '1818',
    size_score: '3',
  },
  {
    name: 'Brock University',
    city: ['St. Catharines', 'Hamilton'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '16352',
    postgrad_count: '1719',
    total_count: '18071',
    year_founded: '1964',
    size_score: '3',
  },
  {
    name: 'Kwantlen Polytechnic University',
    city: ['Richmond', 'Surrey', 'Langley', 'Cloverdale'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '16811',
    postgrad_count: '0',
    total_count: '16811',
    year_founded: '1981',
    size_score: '3',
  },
  {
    name: 'University of Windsor',
    city: ['Windsor'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '12014',
    postgrad_count: '3635',
    total_count: '15649',
    year_founded: '1857',
    size_score: '2',
  },
  {
    name: 'Wilfrid Laurier University',
    city: ['Waterloo', 'Brantford', 'Toronto', 'Kitchener'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '17754',
    postgrad_count: '1667',
    total_count: '15649',
    year_founded: '1911',
    size_score: '2',
  },
  {
    name: 'Thompson Rivers University',
    city: ['Kamloops'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '13072',
    postgrad_count: '100',
    total_count: '13172',
    year_founded: '1970',
    size_score: '2',
  },
  {
    name: 'University of New Brunswick',
    city: ['Fredericton', 'Saint John'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '9061',
    postgrad_count: '1577',
    total_count: '10638',
    year_founded: '1785',
    size_score: '2',
  },
  {
    name: 'Ontario Tech University',
    city: ['Oshawa'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '9315',
    postgrad_count: '669',
    total_count: '9984',
    year_founded: '2002',
    size_score: '2',
  },
  {
    name: 'University of Winnipeg',
    city: ['Winnipeg'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '9394',
    postgrad_count: '453',
    total_count: '9847',
    year_founded: '1871',
    size_score: '2',
  },
  {
    name: 'Trent University',
    city: ['Peterborough', 'Oshawa'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '8880',
    postgrad_count: '557',
    total_count: '9437',
    year_founded: '1963',
    size_score: '2',
  },
  {
    name: 'University of Lethbridge',
    city: ['Lethbridge', 'Edmonton', 'Calgary'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '7930',
    postgrad_count: '300',
    total_count: '8230',
    year_founded: '1967',
    size_score: '2',
  },
  {
    name: 'University of the Fraser Valley',
    city: ['Abbotsford', 'Chilliwack', 'Mission'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '8124',
    postgrad_count: '40',
    total_count: '8164',
    year_founded: '1974',
    size_score: '2',
  },
  {
    name: 'Lakehead University',
    city: ['Thunder Bay', 'Orillia'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '6524',
    postgrad_count: '1198',
    total_count: '7722',
    year_founded: '1965',
    size_score: '2',
  },
  {
    name: "Saint Mary's University",
    city: ['Halifax'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '6904',
    postgrad_count: '682',
    total_count: '7586',
    year_founded: '1802',
    size_score: '2',
  },
  {
    name: 'Capilano University',
    city: ['North Vancouver'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '7500',
    postgrad_count: '0',
    total_count: '7500',
    year_founded: '1968',
    size_score: '2',
  },
  {
    name: 'Vancouver Island University',
    city: ['Nanaimo', 'Duncan', 'Parksville', 'Powell River'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '6116',
    postgrad_count: '163',
    total_count: '6279',
    year_founded: '1969',
    size_score: '2',
  },
  {
    name: 'Yukon University',
    city: ['Whitehorse'],
    province: 'Yukon',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '6030',
    postgrad_count: '0',
    total_count: '6030',
    year_founded: '1983',
    size_score: '2',
  },
  {
    name: 'Saint Francis Xavier University',
    city: ['Antigonish'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '4815',
    postgrad_count: '343',
    total_count: '5158',
    year_founded: '1853',
    size_score: '2',
  },
  {
    name: 'Nipissing University',
    city: ['North Bay', 'Bracebridge', 'Brantford'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '4592',
    postgrad_count: '186',
    total_count: '4778',
    year_founded: '1992',
    size_score: '1',
  },
  {
    name: 'University of Prince Edward Island',
    city: ['Charlottetown'],
    province: 'Prince Edward Island',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '4251',
    postgrad_count: '304',
    total_count: '4555',
    year_founded: '1969',
    size_score: '1',
  },
  {
    name: 'Ontario College of Art and Design University',
    city: ['Toronto'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '4208',
    postgrad_count: '270',
    total_count: '4478',
    year_founded: '1876',
    size_score: '1',
  },
  {
    name: 'Royal Roads University',
    city: ['Victoria'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '887',
    postgrad_count: '3385',
    total_count: '4272',
    year_founded: '1995',
    size_score: '1',
  },
  {
    name: 'Acadia University',
    city: ['Wolfville'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '3607',
    postgrad_count: '647',
    total_count: '4254',
    year_founded: '1838',
    size_score: '1',
  },
  {
    name: 'Mount Saint Vincent University',
    city: ['Halifax'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '2923',
    postgrad_count: '1036',
    total_count: '3959',
    year_founded: '1873',
    size_score: '1',
  },
  {
    name: 'University of Northern British Columbia',
    city: ['Prince George'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '3068',
    postgrad_count: '490',
    total_count: '3558',
    year_founded: '1990',
    size_score: '1',
  },
  {
    name: 'Cape Breton University',
    city: ['Sydney'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '3140',
    postgrad_count: '204',
    total_count: '3334',
    year_founded: '1974',
    size_score: '1',
  },
  {
    name: 'Brandon University',
    city: ['Brandon'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '3140',
    postgrad_count: '120',
    total_count: '3260',
    year_founded: '1899',
    size_score: '1',
  },
  {
    name: 'Trinity Western University',
    city: ['Langley'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '2130',
    postgrad_count: '730',
    total_count: '2860',
    year_founded: '1962',
    size_score: '1',
  },
  {
    name: 'Mount Allison University',
    city: ['Sackville'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '2678',
    postgrad_count: '16',
    total_count: '2694',
    year_founded: '1839',
    size_score: '1',
  },
  {
    name: 'St. Thomas University',
    city: ['Fredericton'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '2494',
    postgrad_count: '0',
    total_count: '2494',
    year_founded: '1910',
    size_score: '1',
  },
  {
    name: 'University College of the North',
    city: ['The Pas', 'Thompson'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '2400',
    postgrad_count: '0',
    total_count: '2400',
    year_founded: '1966',
    size_score: '1',
  },
  {
    name: "Bishop's University",
    city: ['Sherbrooke'],
    province: 'Quebec',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '2442',
    postgrad_count: '20',
    total_count: '2260',
    year_founded: '1843',
    size_score: '1',
  },
  {
    name: 'Emily Carr University of Art and Design',
    city: ['Vancouver'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '1870',
    postgrad_count: '28',
    total_count: '1898',
    year_founded: '1925',
    size_score: '1',
  },
  {
    name: 'Alberta University of the Arts',
    city: ['Calgary'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '1323',
    postgrad_count: '0',
    total_count: '1323',
    year_founded: '1926',
    size_score: '1',
  },
  {
    name: 'Algoma University',
    city: ['Sault Ste', 'Marie'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '1150',
    postgrad_count: '0',
    total_count: '1150',
    year_founded: '2008',
    size_score: '1',
  },
  {
    name: 'Nova Scotia College of Art and Design University',
    city: ['Halifax'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '942',
    postgrad_count: '29',
    total_count: '971',
    year_founded: '1887',
    size_score: '1',
  },
  {
    name: 'Redeemer University College',
    city: ['Ancaster'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '955',
    postgrad_count: '0',
    total_count: '955',
    year_founded: '1982',
    size_score: '1',
  },
  {
    name: "University of King's College",
    city: ['Halifax'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Public',
    undergrad_count: '865',
    postgrad_count: '49',
    total_count: '914',
    year_founded: '1788',
    size_score: '1',
  },
  {
    name: 'Tyndale University',
    city: ['Toronto'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '850',
    postgrad_count: '0',
    total_count: '850',
    year_founded: '1894',
    size_score: '1',
  },
  {
    name: "The King's University",
    city: ['Edmonton'],
    province: 'Alberta',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '790',
    postgrad_count: '0',
    total_count: '790',
    year_founded: '1979',
    size_score: '1',
  },
  {
    name: 'Quest University',
    city: ['Squamish'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '700',
    postgrad_count: '0',
    total_count: '700',
    year_founded: '2007',
    size_score: '1',
  },
  {
    name: 'Crandall University',
    city: ['Moncton'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '685',
    postgrad_count: '0',
    total_count: '685',
    year_founded: '1949',
    size_score: '1',
  },
  {
    name: 'Canadian Mennonite University',
    city: ['Winnipeg'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '600',
    postgrad_count: '0',
    total_count: '600',
    year_founded: '1944',
    size_score: '1',
  },
  {
    name: 'University Canada West',
    city: ['Victoria'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '350',
    postgrad_count: '0',
    total_count: '350',
    year_founded: '2005',
    size_score: '1',
  },
  {
    name: 'Niagara University',
    city: ['Vaughan'],
    province: 'Ontario',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '280',
    postgrad_count: '50',
    total_count: '330',
    year_founded: '2019',
    size_score: '1',
  },
  {
    name: 'Kingswood University',
    city: ['Sussex'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '300',
    postgrad_count: '0',
    total_count: '300',
    year_founded: '1945',
    size_score: '1',
  },
  {
    name: 'Booth University College',
    city: ['Winnipeg'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '250',
    postgrad_count: '0',
    total_count: '250',
    year_founded: '1982',
    size_score: '1',
  },
  {
    name: 'Atlantic School of Theology',
    city: ['Halifax'],
    province: 'Nova Scotia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '0',
    postgrad_count: '124',
    total_count: '124',
    year_founded: '1971',
    size_score: '1',
  },
  {
    name: "St. Stephen's University",
    city: ['St. Stephen'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '100',
    postgrad_count: '0',
    total_count: '100',
    year_founded: '1975',
    size_score: '1',
  },
  {
    name: 'University of Fredericton',
    city: ['Fredericton'],
    province: 'New Brunswick',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '35',
    postgrad_count: '50',
    total_count: '85',
    year_founded: '2005',
    size_score: '1',
  },
  {
    name: 'Fairleigh Dickinson University',
    city: ['Vancouver'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '78',
    postgrad_count: '50',
    total_count: '78',
    year_founded: '2007',
    size_score: '1',
  },
  {
    name: 'New York Institute of Technology',
    city: ['Vancouver'],
    province: 'British Columbia',
    country: 'Canada',
    language: 'English',
    category: 'Private',
    undergrad_count: '70',
    postgrad_count: '40',
    total_count: '70',
    year_founded: '2007',
    size_score: '1',
  },
  {
    name: 'University of Alberta',
    city: ['Edmonton', 'Camrose', 'Calgary'],
    province: 'Alberta',
    country: 'Canada',
    language: 'Bilingual',
    category: 'Public',
    undergrad_count: '31904',
    postgrad_count: '7598',
    total_count: '39502',
    year_founded: '1906',
    size_score: '3',
  },
  {
    name: 'University of Ottawa',
    city: ['Ottawa'],
    province: 'Ontario',
    country: 'Canada',
    language: 'Bilingual',
    category: 'Public',
    undergrad_count: '32150',
    postgrad_count: '6230',
    total_count: '38380',
    year_founded: '1848',
    size_score: '3',
  },
  {
    name: 'University of Manitoba',
    city: ['Winnipeg'],
    province: 'Manitoba',
    country: 'Canada',
    language: 'Bilingual',
    category: 'Public',
    undergrad_count: '23640',
    postgrad_count: '3160',
    total_count: '26800',
    year_founded: '1877',
    size_score: '3',
  },
  {
    name: 'Laurentian University',
    city: ['Sudbury', 'Barrie', 'Hearst', 'Kapuskasing', 'Timmins'],
    province: 'Ontario',
    country: 'Canada',
    language: 'Bilingual',
    category: 'Public',
    undergrad_count: '8174',
    postgrad_count: '869',
    total_count: '9043',
    year_founded: '1960',
    size_score: '2',
  },
  {
    name: 'Royal Military College of Canada',
    city: ['Kingston'],
    province: 'Ontario',
    country: 'Canada',
    language: 'Bilingual',
    category: 'Public',
    undergrad_count: '1040',
    postgrad_count: '660',
    total_count: '1700',
    year_founded: '1876',
    size_score: '1',
  },
];
